AllCops:
  Exclude:
  - 'db/**/*'
  - 'config/**/*'
  - 'script/**/*'
  - 'bin/**/*'
  - 'app/channels/**/*'
  - 'Style/**/*'

Documentation:
  Enabled: false

ClassAndModuleChildren:
  Enabled: false